apiVersion: apps/v1
kind: Deployment
metadata:
  name: mockclient
  namespace: {{ .Values.namespace }}
  labels:
    {{- include "mock-system.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.mockclient.replicas }}
  selector:
    matchLabels:
      app: mockclient
  template:
    metadata:
      labels:
        app: mockclient
    spec:
      containers:
      - name: mockclient
        image: "{{ .Values.mockclient.image.repository }}:{{ .Values.mockclient.image.tag }}"
        imagePullPolicy: Always
        command:
          - "python"
          - "load_tester.py"
          - "--base-url"
          - "http://mockapi:{{ .Values.mockapi.service.port }}"
          - "--success-rate"
          - "{{ .Values.mockclient.env.successRate }}"
          - "--requests-per-second"
          - "{{ .Values.mockclient.env.requestsPerSecond }}"
          - "--variance"
          - "{{ .Values.mockclient.env.variance }}"
        resources:
          requests:
            cpu: 50m
            memory: 64Mi
          limits:
            cpu: 200m
            memory: 128Mi
