apiVersion: apps/v1
kind: Deployment
metadata:
  name: mockapi
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "mock-system.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.mockapi.replicas }}
  selector:
    matchLabels:
      app: mockapi
  template:
    metadata:
      labels:
        app: mockapi
    spec:
      containers:
      - name: mockapi
        image: "{{ .Values.mockapi.image.repository }}:{{ .Values.mockapi.image.tag }}"
        imagePullPolicy: Always
        ports:
        - containerPort: 8082
        command: ["python", "-m"]
        args: ["uvicorn", "app:app", "--host", "0.0.0.0", "--port", "8082"]
        resources:
          requests:
            cpu: 50m
            memory: 64Mi
          limits:
            cpu: 200m
            memory: 128Mi
        env:
        - name: BASE_LATENCY
          value: "0.042"
        livenessProbe:
          httpGet:
            path: /success
            port: 8082
          initialDelaySeconds: 30
          periodSeconds: 30
          timeoutSeconds: 10
          failureThreshold: 3